#### Load the CSV Locally

In [2]:
import pandas as pd

df = pd.read_csv('../data/cleaned/cleaned_bigfive_v1.csv')
df.head()

,EXT1,EXT2,EXT3,EXT4,EXT5,EXT6,EXT7,EXT8,EXT9,EXT10,...,endelapse,IPC,country,lat_appx_lots_of_err,long_appx_lots_of_err,Extraversion,Neuroticism,Agreeableness,Conscientiousness,Openness
0,4.0,1.0,5.0,2.0,5.0,1.0,5.0,2.0,4.0,1.0,...,6,1,GB,51.5448,0.1991,3.0,2.4,3.1,3.2,3.3
1,3.0,5.0,3.0,4.0,3.0,3.0,2.0,5.0,1.0,5.0,...,11,1,MY,3.1698,101.706,3.4,2.1,3.2,3.1,2.7
2,2.0,3.0,4.0,4.0,3.0,2.0,1.0,3.0,2.0,5.0,...,7,1,GB,54.9119,-1.3833,2.9,2.6,2.8,2.8,3.1
3,2.0,2.0,2.0,3.0,4.0,2.0,2.0,4.0,1.0,4.0,...,7,1,GB,51.75,-1.25,2.6,2.7,3.2,2.7,3.1
4,3.0,3.0,4.0,2.0,4.0,2.0,2.0,3.0,3.0,4.0,...,3,1,SE,59.3333,18.05,3.0,2.2,2.8,2.9,3.2

In [3]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 602587 entries, 0 to 602586
Columns: 115 entries, EXT1 to Openness
dtypes: float64(109), int64(2), object(4)
memory usage: 528.7+ MB

,EXT1,EXT2,EXT3,EXT4,EXT5,EXT6,EXT7,EXT8,EXT9,EXT10,...,screenh,introelapse,testelapse,endelapse,IPC,Extraversion,Neuroticism,Agreeableness,Conscientiousness,Openness
count,602587.000000,602587.000000,602587.000000,602587.000000,602587.000000,602587.000000,602587.000000,602587.000000,602587.000000,602587.000000,...,602587.000000,6.025870e+05,6.025870e+05,6.025870e+05,602587.0,602587.000000,602587.000000,602587.000000,602587.000000,602587.000000
mean,2.576790,2.848214,3.230647,3.219377,3.248359,2.424186,2.710744,3.469570,2.954227,3.622079,...,822.142920,1.030063e+03,6.401222e+02,3.690669e+03,1.0,3.030420,3.047360,3.167351,3.143114,3.309093
std,1.238104,1.306037,1.191720,1.205208,1.246890,1.214580,1.370067,1.239486,1.324939,1.263787,...,185.610193,5.920930e+04,1.650952e+04,1.925467e+06,0.0,0.332876,0.641163,0.345323,0.375442,0.365255
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.000000,1.000000e+00,2.000000e+01,1.000000e+00,1.0,1.000000,1.000000,1.000000,1.000000,1.000000
25%,1.000000,2.000000,2.000000,2.000000,2.000000,1.000000,1.000000,3.000000,2.000000,3.000000,...,667.000000,5.000000e+00,1.700000e+02,9.000000e+00,1.0,2.800000,2.600000,3.000000,2.900000,3.100000
50%,3.000000,3.000000,3.000000,3.000000,3.000000,2.000000,3.000000,4.000000,3.000000,4.000000,...,768.000000,1.100000e+01,2.200000e+02,1.300000e+01,1.0,3.000000,3.000000,3.200000,3.100000,3.300000
75%,3.000000,4.000000,4.000000,4.000000,4.000000,3.000000,4.000000,5.000000,4.000000,5.000000,...,900.000000,3.100000e+01,3.040000e+02,1.700000e+01,1.0,3.200000,3.500000,3.400000,3.400000,3.600000
max,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,...,8802.000000,2.944307e+07,5.372971e+06,1.493327e+09,1.0,5.000000,5.000000,5.000000,5.000000,5.000000

In [4]:
import seaborn as sns
import matplotlib.pyplot as plt